// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module("angular_sis");

  app.config([
    "$httpProvider", function($httpProvider) {
      return $httpProvider.defaults.headers.common["X-CSRFToken"] = csrf_token;
    }
  ]);

  app.config(function(RestangularProvider) {
    RestangularProvider.setBaseUrl("/api");
    RestangularProvider.setRequestSuffix("/");
    RestangularProvider.addResponseInterceptor(function(data, operation, what, url, response, deferred) {
      var extractedData;
      extractedData = void 0;
      if (operation === "getList" && data["results"] !== void 0) {
        extractedData = data.results;
        extractedData.meta = {};
        extractedData.meta['count'] = data.count;
        extractedData.meta['next'] = data.next;
        extractedData.meta['previous'] = data.previous;
      } else {
        extractedData = data;
      }
      return extractedData;
    });
  });

  app.config(function($routeProvider, $locationProvider) {
    $routeProvider.when("/course/course_section_grades/:course_section_id/", {
      controller: "CourseGradesController"
    });
    $routeProvider.when("/course/student_grades/:student_id/", {
      templateUrl: '/static/app/partials/student_grades.html',
      controller: "StudentGradesController"
    });
    $routeProvider.when("/course/student_grades/:student_id/:year_id/", {
      templateUrl: '/static/app/partials/student_grades.html',
      controller: "StudentGradesController"
    });
    $routeProvider.when("/schedule/course/", {
      templateUrl: '/static/app/partials/course_detail.html',
      controller: "CourseController",
      reloadOnSearch: false
    });
    return $locationProvider.html5Mode(true);
  });

}).call(this);
